# Generated by Django 6.0.7 on 2026-07-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_incidentdialyse_userincidentdialyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
