# Generated by Django 5.1 on 2026-07-15 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_categorieequipement_equipement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'archivage")),
                ('pdf_file', models.FileField(upload_to='patient_archives/', verbose_name="Fichier PDF de l'archive")),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Archivé par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='apps.patient', verbose_name='Patient concerné')),
            ],
            options={
                'verbose_name': 'Archive de Patient',
                'verbose_name_plural': 'Archives de Patients',
                'ordering': ['-archived_at'],
            },
        ),
    ]
