# Generated by Django 5.1 on 2026-07-15 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_patientarchive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Nom du shift')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début attendue')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin attendue')),
                ('marge_retard', models.IntegerField(default=15, verbose_name='Marge de retard (en minutes)')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date planifiée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.shift', verbose_name='Shift')),
            ],
            options={
                'ordering': ['-date', 'user'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée réelle")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ réelle')),
                ('statut', models.CharField(choices=[('PRESENT', "Présent (À l'heure)"), ('RETARD', 'En Retard'), ('ABSENT', 'Absent')], default='ABSENT', max_length=15)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Commentaires/Justifications')),
                ('planning', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presence', to='apps.planning', verbose_name='Planning associé')),
            ],
        ),
    ]
